//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorCare.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilityOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacilityOption()
        {
            this.FacilitiesOptions = new HashSet<FacilitiesOption>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int FacilityOptionTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacilitiesOption> FacilitiesOptions { get; set; }
        public virtual FacilityOptionType FacilityOptionType { get; set; }
    }
}
